apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ default .Values.deployment.name .Values.serviceAccount.name }}
      {{- end }}
      {{- with .Values.deployment.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: admin
              containerPort: 8080
            - name: metrics
              containerPort: 8888
            - name: dd-agent-ingest
              containerPort: 8126
            - name: exporter-api
              containerPort: 18081
          env:
            - name: MDAI_ADMIN_ADDR
              value: {{ .Values.env.adminAddr | quote }}
            - name: MDAI_METRICS_ADDR
              value: {{ .Values.env.metricsAddr | quote }}
            {{- if .Values.env.datadogAgentIngestAddr }}
            - name: MDAI_DATADOG_AGENT_INGEST_ADDR
              value: {{ .Values.env.datadogAgentIngestAddr | quote }}
            {{- end }}
            - name: MDAI_EXPORTER_API_ADDR
              value: {{ .Values.env.exporterAPIAddr | quote }}
            - name: MDAI_RETENTION
              value: {{ .Values.env.retention | quote }}
            {{- if .Values.env.configReloadInterval }}
            - name: MDAI_CONFIG_RELOAD_INTERVAL
              value: {{ .Values.env.configReloadInterval | quote }}
            {{- end }}
            {{- if .Values.config.enabled }}
            - name: MDAI_FIDELITY_RULES_PATH
              value: {{ printf "%s/fidelity-policy.yaml" .Values.config.mountPath | quote }}
            - name: MDAI_FIDELITY_FIELD_MAPPING_PATH
              value: {{ printf "%s/field-mapping.yaml" .Values.config.mountPath | quote }}
            {{- end }}
          {{- if .Values.config.enabled }}
          volumeMounts:
            - name: validator-config
              mountPath: {{ .Values.config.mountPath | quote }}
              readOnly: true
          {{- end }}
      {{- if .Values.config.enabled }}
      volumes:
        - name: validator-config
          configMap:
            name: {{ .Values.config.name }}
      {{- end }}
