serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

deployment:
  name: mdai-fidelity-validator
  replicas: 1
  annotations: {}
  podAnnotations: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []

image:
  repository: ghcr.io/mydecisive/mdai-fidelity-validator
  tag: 0.1.0
  pullPolicy: IfNotPresent

env:
  adminAddr: ":8080"
  metricsAddr: ":8888"
  datadogAgentIngestAddr: ":8126"
  exporterAPIAddr: ":18081"
  retention: "30m"
  configReloadInterval: "15s"

config:
  enabled: true
  mountPath: /etc/mdai-config
  name: mdai-fidelity-validator-config

service:
  name: mdai-fidelity-validator
  type: ClusterIP
  annotations: {}
  labels: {}
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: dd-agent-ingest
      port: 8126
      targetPort: 8126
      protocol: TCP
    - name: exporter-api
      port: 18081
      targetPort: 18081
      protocol: TCP

serviceMonitor:
  enabled: false
  namespace: ""
  labels: {}
  annotations: {}
  interval: "5s"
  scrapeTimeout: "1s"
  honorLabels: true
  path: /metrics
  scheme: http
  targetLabels: []
  podTargetLabels: []
  relabelings: []
  metricRelabelings: []
